### ISSUE TITLE
Repeatably Denied Access

### ISSUE THREAD

**Issue by atamanje** [groupgets/GetThermal#9] opened 2018-07-11 21:56 UTC
Hello, 

I am trying to use GetThermal on OpenSUSE 42.3. I have QT 5.11.1 installed and I am able to get the application to run, however, I am running Linux through Virtual Box. GetThermal builds correctly and reads the camera successfully but, no image is seen in the application. In the application output it reads, "uvc_open: Access denied (-3)".

Any help to solve this issue is appreciated. I have run qtcreator using the sudo command in the terminal but, it reports some text and is then aborted. I have also tried to run Virtual Box as an administrator on the computer I'm using and that has not helped. I have attached a screenshot of qtcreator and GetThermal as I was running Virtal Box using 'Run as Administrator'.

Thanks, 
Jessie A
![issue](https://user-images.githubusercontent.com/39246878/42601413-88f3af36-8533-11e8-89d8-7a486561487f.jpg)

**Comment by kekiefer** [comment] 2018-07-11 22:11
Is this a duplicate of #8?

**Comment by atamanje** [comment] 2018-07-13 17:35
Not exactly, I think I've narrowed down the problem to not running QtCreator using a sudo command. When I try to do this in the terminal, the action is aborted. My colleagues were able to use GetThermal properly using Ubuntu but, I am using OpenSUSE. Would you be able you suggest a fix, so that I can run QtCreator using the command 'sudo qtcreator'.
![image](https://user-images.githubusercontent.com/39246878/42705539-a256a84c-86a1-11e8-8221-73cb02889791.png)

**Comment by kekiefer** [comment] 2018-07-13 18:04
Did you see the part in there that sets up the UDEV rules to give the non-root user permissions to control the USB device?

**Comment by atamanje** [comment] 2018-07-13 18:13
About the UDEV rule, I entered the sudo command from one of the other closed issues, "sudo sh -c "echo 'SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"1e4e\", ATTRS{idProduct}==\"0100\", SYMLINK+=\"pt1\", GROUP=\"usb\", MODE=\"666\"' > /etc/udev/rules.d/99-pt1.rules""

and I tried running QtCreator using, "sudo DISPLAY=:0 ./GetThermal" which refers to GetThermal program in a debug directory (see image 1). This results in an I/O error (see image 2).

Image 1:
![image](https://user-images.githubusercontent.com/39246878/42706906-63c1443e-86a6-11e8-93b8-974a6ddef593.png)
Image 2:
![image](https://user-images.githubusercontent.com/39246878/42706983-b500aeac-86a6-11e8-9174-d33e539ec78a.png)

**Comment by atamanje** [comment] 2018-07-13 18:14
And even though I've run the UDEV rule command the "sudo qtcreator" command continues to get aborted, saying, "Could not connect to any X display."

**Comment by kekiefer** [comment] 2018-07-13 18:22
if you're set up udev to give your user permissions to access usb, you don't need to run stuff as sudo anymore.

**Comment by atamanje** [comment] 2018-07-13 18:34
Okay. So I feel like I almost have it. I am no longer denied access, which is great but, I still get an I/O error (uvc_open: I/O error (-1)) in QtCreator. What could be the cause of this?

![image](https://user-images.githubusercontent.com/39246878/42707920-a78c96f2-86a9-11e8-8149-f194b52fb66a.png)

**Comment by kekiefer** [comment] 2018-07-13 18:38
So the same as #8. Please review that solution again and see if it works for you.

**Comment by atamanje** [comment] 2018-07-13 18:52
Hmm. I looked at #8 again and I tried doing a rebuild to see if I too was trying to run on a broken build but, I still get that I/O error.

**Comment by kekiefer** [comment] 2018-07-24 19:42
Well, I don't know. There is a Linux AppImage binary in releases that you could try (presuming it works on OpenSUSE). This might help to see if it's a build or platform issue.

**Comment by kekiefer** [comment] 2018-08-24 17:48
Any update or should I close this?

**Closed** 2018-12-01 18:10 UTC

**Comment by soltnerXavier2** [comment] 2022-03-01 12:51
I have a potential fix for this.

I had the same issue  :
![Screenshot_20220301_134703](https://user-images.githubusercontent.com/100694391/156171543-a320bebd-02e0-48d1-8ad7-78e20ab8ee31.png)
:
[Potential origin]
My guess is that the application do not have superuser right to acces uvc.

[Solution]
 - Find your executable application by going through QT : Project -> Run ->Locate the section "Run" and line "Executable /home/....." -> This is your path to your executable.
 - Go where your executable is located
 - Run the executable with "sudo ./GetThermal"
